export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
export const IS_LOGIN = 'IS_LOGIN';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ITEMMASTER_SUCCESS = 'GET_ITEMMASTER_SUCCESS';

export const GET_BUSINESSES = 'GET_BUSINESSES';
export const SELECT_ROUTE_SUCCESS = 'SELECT_ROUTE_SUCCESS'
export const GET_ROUTES = 'GET_ROUTES';
export const GET_USERS = 'GET_USERS';
export const GET_ORDERS = 'GET_ORDERS';

export const CHECKIN_COMPLETE = 'CHECKIN_COMPLETE';
export const GET_CHECKINS_SUCCESS = 'GET_CHECKINS_SUCCESS';
export const RETRIEVED_CHECKIN_SUCCESS = 'RETRIEVED_CHECKIN_SUCCESS';
export const CURRENT_CHECKIN_INFO = 'CURRENT_CHECKIN_INFO';
export const CREATE_CHECKIN_SUCCESS = 'CREATE_CHECKIN_SUCCESS';
export const CHECKIN_UPDATE_SUCCESS = 'CHECKIN_UPDATE_SUCCESS';


export const REFRESH = 'REFRESH';